"""Tool approval contract (phase 3 — Tool Security).

The approval boundary between the tool loop and the transport. The loop only
ever talks to the :class:`ToolApprovalProvider` protocol and the value objects
here — it never knows about inline keyboards, Telegram callbacks, or the
database. The Telegram implementation of the provider is
:mod:`..telegram.approval` (an in-memory broker that presents Approve/Deny
buttons and waits on an ``asyncio`` future).

The contract is deliberately **channel-agnostic and stdlib-only**: it imports
nothing from Telegram, the OpenAI SDK, or SQLAlchemy.

``ApprovalRequest`` carries only what a human needs to judge *this one call* —
an opaque request id, the conversation, a short **hashed** principal identity,
the tool name, a **safe summary**, and the **arguments** to be executed. The
summary is produced by :meth:`Tool.approval_summary` and describes the tool's
*purpose* (shown on the card under "What it does:"); it does not need to
include the arguments, because the provider shows those separately (as a
readable "Arguments:" block) from ``request.arguments`` — the already
schema-validated mapping the loop is about to execute. A provider that renders
the card is responsible for keeping the arguments out of logs, the audit
table, and any model-facing error text; the loop and auditor enforce that
independently of the provider.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Protocol, runtime_checkable


class ApprovalDecision(str, Enum):
    """The outcome of a one-time human approval wait."""

    APPROVED = "approved"
    DENIED = "denied"
    EXPIRED = "expired"


@dataclass(frozen=True)
class ApprovalRequest:
    """Everything the approval provider needs to present and bind one approval.

    * ``request_id`` — an opaque, random id (generated by the loop via
      ``secrets.token_urlsafe``); the provider uses it as the key that binds the
      pending wait to the eventual callback. The loop treats it as opaque.
    * ``conversation_id`` — the conversation the call belongs to. The provider
      resolves the *transport* chat to deliver the prompt from this (e.g. via the
      repository) — the loop never knows the Telegram chat id.
    * ``scope`` — the raw, opaque principal identity (e.g. ``telegram:<user_id>``).
      The provider is responsible for hashing it (via the shared ``hash_scope``)
      to a short fingerprint for binding; the raw scope is never persisted.
    * ``tool_name`` — the tool being approved (shown to the human, verbatim).
    * ``summary`` — the safe, human-readable summary (see :meth:`Tool.approval_summary`).
    * ``expires_at`` — the deadline the provider must enforce.
    * ``arguments`` — the **already schema-validated** arguments the loop is about
      to execute with. The provider may show them to the human (e.g. formatted as
      readable JSON) so they can judge this specific call; the loop only ever
      gets here *after* JSON-Schema validation, so these are well-formed. The
      provider must keep them out of logs / the audit table / model-facing error
      text (those invariants live in the loop and auditor, not here).
    """

    request_id: str
    conversation_id: int
    scope: str
    tool_name: str
    summary: str
    expires_at: datetime
    arguments: dict[str, Any] = field(default_factory=dict)
    # Extra context the provider may need (kept opaque; nothing sensitive).
    metadata: dict[str, Any] = field(default_factory=dict)


@runtime_checkable
class ToolApprovalProvider(Protocol):
    """The loop's only view of human approval (channel-agnostic).

    ``request_approval`` blocks (awaits) until the human decides, the request
    expires, or the provider is shut down. It **must not** busy-poll, block the
    event loop, or perform network I/O beyond what the transport itself does to
    present/resolve the approval. A :class:`ApprovalDecision` is always returned
    — a timeout is :attr:`ApprovalDecision.EXPIRED`, a denied click
    ``DENIED``, a valid click ``APPROVED``.
    """

    async def request_approval(self, request: ApprovalRequest) -> ApprovalDecision:
        """Present ``request`` and await the one-time human decision."""
        ...

    async def shutdown(self) -> None:
        """Cancel all pending approvals; any waiting caller resolves (EXPIRED)."""
        ...
