"""Tool approval contract (phase 3 — Tool Security).

The approval boundary between the tool loop and the transport. The loop only
ever talks to the :class:`ToolApprovalProvider` protocol and the value objects
here — it never knows about inline keyboards, Telegram callbacks, or the
database. The Telegram implementation of the provider is
:mod:`..telegram.approval` (an in-memory broker that presents Approve/Deny
buttons and waits on an ``asyncio`` future).

The contract is deliberately **channel-agnostic and stdlib-only**: it imports
nothing from Telegram, the OpenAI SDK, or SQLAlchemy.

``ApprovalRequest`` carries only what a human needs to judge *this one call* —
an opaque request id, the conversation, a short **hashed** principal identity,
the tool name, and a **safe summary**. The summary is produced by
:meth:`Tool.approval_summary` and, by default, reveals *only* the tool name and
a fixed "arguments not shown" note. A future high-risk tool that must show a
human what it is about to do is responsible for generating its own reviewed,
secret-free summary — it must **never** dump raw JSON arguments by default.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Protocol, runtime_checkable


class ApprovalDecision(str, Enum):
    """The outcome of a one-time human approval wait."""

    APPROVED = "approved"
    DENIED = "denied"
    EXPIRED = "expired"


@dataclass(frozen=True)
class ApprovalRequest:
    """Everything the approval provider needs to present and bind one approval.

    * ``request_id`` — an opaque, random id (generated by the loop via
      ``secrets.token_urlsafe``); the provider uses it as the key that binds the
      pending wait to the eventual callback. The loop treats it as opaque.
    * ``conversation_id`` — the conversation the call belongs to. The provider
      resolves the *transport* chat to deliver the prompt from this (e.g. via the
      repository) — the loop never knows the Telegram chat id.
    * ``scope`` — the raw, opaque principal identity (e.g. ``telegram:<user_id>``).
      The provider is responsible for hashing it (via the shared ``hash_scope``)
      to a short fingerprint for binding; the raw scope is never persisted.
    * ``tool_name`` — the tool being approved (shown to the human, verbatim).
    * ``summary`` — the safe, human-readable summary (see :meth:`Tool.approval_summary`).
    * ``expires_at`` — the deadline the provider must enforce.
    """

    request_id: str
    conversation_id: int
    scope: str
    tool_name: str
    summary: str
    expires_at: datetime
    # Extra context the provider may need (kept opaque; nothing sensitive).
    metadata: dict[str, Any] = field(default_factory=dict)


@runtime_checkable
class ToolApprovalProvider(Protocol):
    """The loop's only view of human approval (channel-agnostic).

    ``request_approval`` blocks (awaits) until the human decides, the request
    expires, or the provider is shut down. It **must not** busy-poll, block the
    event loop, or perform network I/O beyond what the transport itself does to
    present/resolve the approval. A :class:`ApprovalDecision` is always returned
    — a timeout is :attr:`ApprovalDecision.EXPIRED`, a denied click
    ``DENIED``, a valid click ``APPROVED``.
    """

    async def request_approval(self, request: ApprovalRequest) -> ApprovalDecision:
        """Present ``request`` and await the one-time human decision."""
        ...

    async def shutdown(self) -> None:
        """Cancel all pending approvals; any waiting caller resolves (EXPIRED)."""
        ...


# A fixed, non-instructional note shown when a tool does not supply a custom
# summary. It deliberately says the arguments are withheld — the human judges
# the *capability*, not the specific parameters, for any tool that has not opted
# into a reviewed summary.
DEFAULT_APPROVAL_SUMMARY = "Arguments are not shown for your safety."
